<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <h4 class="text-primary text-uppercase mb-1">
                    Cliente: <?=$ultimaVenta->Cliente()->nombre?></h4>
                <br>
                <h6 class="card-title">Email: <?=$ultimaVenta->Cliente()->email?></h6>
                <h6 class="card-title">Teléfono: <?=$ultimaVenta->Cliente()->telefono?></h6>
                <h6 class="card-title">Total Actual: $<?=$totalTemp?></h6>
                <h6 class="card-title">Comentario de Venta: <?=$ultimaVenta->comentario?></h6>

            </div>
            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
        </div>
    </div>
</div>