<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>
    <div class="col-1">
        <?= Formbs::link_regresar("categorias",  "categorias/registrar", "👨‍👩‍👧‍👦"); ?>
    </div>
</div>
<br>


<h2>Categorias</h2>

<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>id</th>
        <th>Nombre</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($categorias as $p):?>
        <tr>
            <td>
                <?= Html::link("categorias/ver/{$p->id}", "Ver", ["title" => "Ir a producto.."]) ?>
            </td>
            <td><?= $p->nombre?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>