<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>
    <div class="col-1">
        <?= Formbs::link_regresar("Venta",  "ventas/registrar", "📈"); ?>

    </div>

    <div class="col-1">
        <?= Formbs::link_regresar("Nueva",  "ventas/nueva", "📈"); ?>

    </div>
</div>
<br>


<h2>Ventas</h2>

<table class="table table-striped table-hover myTable">-
    <thead>
    <tr>
        <th>Id</th>
        <th>Id de Clientes</th>
        <th>Id de Empleados</th>
        <th>Metodos de Pago</th>
        <th>Fecha</th>
        <th>Total</th>
        <th>Por Pagar</th>
        <th>Comentario</th>
        <th>Cancelada</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($ventas as $p):?>
        <tr>
            <td>
                <?= Html::link("ventas/ver/{$p->id}", "Ver", ["title" => "Ir a la venta.."]) ?>
            </td>
            <td><?= $p->getcliente()->nombre?></td>
            <td><?= $p->getVendedor()->nombre?></td>
            <td><?= $p->getmetodoP()->nombre?></td>
            <td><?= $p->fecha?></td>
            <td><?= $p->total?></td>
            <td><?= $p->por_pagar?></td>
            <td><?= $p->comentario?></td>
            <td><?= $p->cancelada?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>