
<style>
    .error {
        color: #5a5c69;
        font-size: 1.7rem;
        position: relative;
        line-height: 1.15;
        width: 60.1rem;
    }
</style>

<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar("Ventas",  "ventas"); ?>
    </div>
</div>
<br>

<?= Form::open() ?>
<h2>Ventas</h2>

<div class="row">
    <div class="col-4">
        <label>Cliente *</label>
        <?= Formbs::seleccion("venta.clientes_id", "Cliente", $clientes)?>
        <br>

        <label>Empleado *</label>
        <?= Formbs::seleccionemp("venta.empleados_id", "Empleado", $empleados)?>

        <?= Formbs::total("venta.total",null,0)?>
        <?= Formbs::total("venta.por_pagar",null,0)?>
        <?= Formbs::total("venta.cancelada",null,1)?>
    </div>
    <div class="col-4">
        <?= Formbs::numeroUS('venta.usuario_id')?>

        <label>Id del Metodo de Pago *</label>
        <?= Formbs::seleccion("venta.metodos_pago_id", "Metodo", $metodos)?>

        <br>

        <label>Fecha *</label>
        <?= Formbs::fecha('venta.fecha', null, date("Y-m-d")) ?>
    </div>

    <div class="col-4">

        <label>Comentario</label>
        <?= Formbs::txt('venta.comentario', null, 1)?>
    </div>
</div>
<br>

<?php View::content(); ?>
<br>
<?= View::partial("botones/Btn_Form", null)?>

<?= Form::close() ?>


