<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>
    <div class="col-1">
        <?= Formbs::link_regresar("Empleado",  "empleados/registrar", "🧑‍💼"); ?>
    </div>
</div>
<br>

<h2>Empleados</h2>

<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Email</th>
        <th>Teléfono</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($empleados as $p):?>
        <tr>
            <td>
                <?= Html::link("empleados/ver/{$p->id}", "Ver", ["title" => "Ir a producto.."]) ?>
            </td>
            <td><?= $p->nombre?></td>
            <td><?= $p->email?></td>
            <td><?= $p->telefono?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>