<h1>Total abonado: $<?=number_format(max(0, $total_a_abonar),2)?></h1>

<table class="table table-sm table-hover">
    <thead>
    <tr>
        <th>id</th>
        <th>Fecha</th>
        <th>Total</th>
        <th>Abonado</th>
        <th>Por Pagar</th>
        <th>Comentario Por Venta</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($ventas_a_pagar as $v): ?>
        <tr>
            <td><?=$v->id?></td>
            <td><?=$v->created_at?></td>
            <td><?=($v->total)?></td>
            <td><?=$v->a_abonar?></td>
            <td><?= number_format(max(0, $v->por_pagar), 2) ?></td>
            <td><?=$v->comentario?></td>
        </tr>

        <?php endforeach; ?>

    </tbody>
</table>
<br>
<div class="row">
    <div class="col-3">
        <?=View::partial("pagos/Card_Comentario", null,["ComentarioGImprimir" => $ComentarioGImprimir])?>
    </div>
</div>

<br>
<br>
<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar("Pagos",  "pagos"); ?>
    </div>
    <div class="col-1">
        <?= Formbs::link_abonar("Abonar",  $cliente->id, "💰"); ?>
    </div>
</div>

<br>



