<h1>Total a abonar: $<?=number_format($total_a_abonar)?></h1>

<table class="table table-sm table-hover">
    <thead>
    <tr>
        <th>id</th>
        <th>Fecha</th>
        <th>Total</th>
        <th>Abonado</th>
        <th>Por Pagar</th>
        <th>A Pagar</th>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($ventas_a_pagar as $v): ?>
        <tr>
            <td><?=$v->id?></td>
            <td><?=$v->created_at?></td>
            <td><?=($v->total)?></td>
            <td><?=($v->total - $v->por_pagar)?></td>
            <td><?=$v->por_pagar?></td>
            <td><?=$v->a_abonar?></td>
        </tr>

    <?php endforeach; ?>

    </tbody>
</table>