<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>

    <div class="col-1">
        <?= Formbs::link_regresar("Pagos",  "pagos/nuevo", "💸"); ?>

    </div>
</div>
<br>


<h2>Pagos</h2>

<table class="table table-striped table-hover myTable">-
    <thead>
    <tr>
        <th>Id</th>
        <th>Nombre del Cliente</th>
        <th>Metodo de Pago</th>
        <th>Total</th>
        <th>Comentario General</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($pagos as $p):?>
        <tr>
            <td>
                <?= Html::link("ventas/ver/{$p->id}", "Ver", ["title" => "Ir a la venta.."]) ?>
            </td>
            <td><?= $p->getVc()->getCliente()->nombre?></td>
            <td><?= $p->getVc()->getMetodoP()->nombre?></td>
            <td><?= $p->total?></td>
            <td><?= $p->comentario?></td>


        </tr>
    <?php endforeach;?>
    </tbody>
</table>