<table class="table table-hover table-sm">
    <thead>
    <th>Total de unidades vendidas</th>
    <th>Total de ingresos generados por el producto</th>
    <th>Última fecha de venta</th>
    </thead>
    <tbody>
        <tr>
            <td><?= $EST['total_unidades_vendidas'] ?></td>
            <td><?= $EST['total_ingresos']?></td>
            <td><?= $EST['ultima_fecha_venta']?></td>
        </tr>
    </tbody>
</table>