<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>
    <div class="col-1">
        <?= Formbs::link_regresar("Producto",  "productos/registrar", "👕"); ?>
    </div>
</div>
<br>

<h2>Productos</h2>
<table class="table table-striped table-hover myTable">
    <thead>
        <tr>
            <th>id</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Stock</th>
            <th>Categorías</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($productos as $p):?>
        <tr>
            <td>
                <?= Html::link("productos/ver/{$p->id}", "Ver", ["title" => "Ir a producto.."]) ?>
            </td>
            <td><?= $p->nombre?></td>
            <td><?= $p->precio?></td>
            <td><?= $p->stock?></td>
            <td><?= $p->getCategoria()->nombre?></td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>

