<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar("Productos",  "productos"); ?>
    </div>
</div>

<br>

<?= View::partial("productos/card", null, ["productos" => $productos])?>

<div class="row">
    <div class="col-12">
        <h1 class="text-center">Tablas de información</h1>
    </div>

</div>


<div class="row">
    <div class="col-6">
        <strong>Detalle de Ventas del producto</strong>

        <?= View::partial("productos/productos", null, ["productos" => $productos->getdetalleproducto()])?>

    </div>

    <div class="col-6">
        <strong>Información básica del producto</strong>
        <table class="table table-hover table-sm">
            <thead>
            <th>Cantidad</th>
            <th>Descripción</th>
            <th>IVA</th>
            <th>Unitario</th>
            </thead>
            <tbody>
            <tr>
                <td>1</td>
                <td><?=$productos->nombre?></td>
                <td><?=($productos->precio)*.16?></td>
                <td><?=$productos->precio?></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

<br>

<div class="row">
    <div class="col-6">
        <strong>Información de ventas del producto</strong>
        <?= View::partial("productos/info_venta", null, ["productos" => $productos->getdetalleproducto(), "EST"=>$EST])?>
    </div>
    <div class="col-6">
        <strong>Movimientos de stock</strong>
        <?= View::partial("productos/info_stock", null, ["productos" => $productos, "EST"=>$EST])?>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <h2 class="text-center">Visualización</h2>
    </div>
    <div class="col-6">
        <h3 class="text-center"><?=$productos->nombre?> vs Ventas Totales</h3>
        <?= View::partial("productos/pastel1", null, ["productos" => $productos->getdetalleproducto(), "total"=>$Tot, "nombre"=>$productos->nombre, "EST"=>$EST])?>

    </div>
    <div class="col-6">
        <h3 class="text-center">Ventas Mensuales</h3>
        <?= View::partial("productos/grafica", null, ["productos" => $productos->getdetalleproducto(), "total"=>$Tot, "nombre"=>$productos->nombre, "EST"=>$EST, "ventas_por_mes"=>$ventas_por_mes])?>
    </div>
</div>

<a href="/kumbiaphp/default/public/productos" class="btn btn-primary">Ir a Productos</a>
