<div class="card" style="width:100%;">
    <div class="card-body">
        <h5 class="card-title">Cliente <?=$clientes->id ?> - <?=$clientes->nombre?></h5>
        <!-- <h6 class="card-subtitle mb-2 text-muted">< ? = ? ></h6> -->
        <p class="card-text">
        <ul>
            <li>Email: <?=$clientes->email?></li>
            <li>Telefono: <?=$clientes->telefono?> </li>
        </ul>
        </p>
    </div>
</div>


