<div class="row justify-content-center">
    <div class="col-8">
        <h4 class="text-center">Otras Categorías vs <?=$categorias->nombre?></h4>
        <canvas id="ingresosComparacionChart" style="width:100%; height:200px;"></canvas>
    </div>

</div>
<script>
    const categoriasIngresos = ["Otras Categorías", "<?= htmlspecialchars($categorias->nombre) ?>"];
    const ingresos = [<?= $ingresos_otros ?>, <?= $ingresos_categoria ?>];
    // Gráfico de Pastel: Comparación de Ingresos
    new Chart(document.getElementById('ingresosComparacionChart').getContext('2d'), {
        type: 'pie',
        data: {
            labels: categoriasIngresos,
            datasets: [{
                data: ingresos,
                backgroundColor: ['#FFCE56', '#4BC0C0']
            }]
        },
        options: { responsive: true }
    });

</script>