<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>
    <div class="col-1">
        <?= Formbs::link_regresar("Metodo de Pago",  "metodosPago/registrar", "💰"); ?>

    </div>
</div>
<br>

<h2>Métodos de Pago</h2>

<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($metodosPago as $p):?>
        <tr>
            <td>
                <?= Html::link("metodosPago/ver/{$p->id}", "Ver", ["title" => "Ir a producto.."]) ?>
            </td>
            <td><?= $p->nombre?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>