<style>
    .imagen-circular {
        width: 200px;
        height: 200px;
        border-radius: 50%; /* Hace que la imagen sea circular */
        object-fit: cover; /* Ajusta la imagen sin deformarla */
        display: block;
        margin: auto; /* Centrar en la página */
    }
</style>

<div class="row">
    <div class="col-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <h4 class="text-primary text-uppercase mb-1">
                            Kevin Jacobo</h4>
                        <br>
                        <h6 class="card-title">Carrera: Ingeniería en Sistemas Computacionales</h6>
                        <h6 class="card-title">Materia: Programación Web</h6>
                        <h6 class="card-title">Número de control: 21590387</h6>
                    </div>
                    <img src="<?=URL_APP?>/default/public/storage/personal/foto.jpg" class="imagen-circular">



                </div>
            </div>
        </div>
    </div>
</div>