<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>

    <div class="col-1">
        <?= Formbs::link_regresar("Pagos",  "pagos/nuevo", "💸"); ?>

    </div>
</div>
<br>


<h2>Pagos Items</h2>

<table class="table table-striped table-hover myTable">-
    <thead>
    <tr>
        <th>Id</th>
        <th>Id del Pago</th>
        <th>Id de la venta</th>
        <th>Antes</th>
        <th>Monto Pagado</th>
        <th>Adeudo</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($pagositems as $p):?>
        <tr>
            <td>
                <?= Html::link("ventas/ver/{$p->id}", "Ver", ["title" => "Ir a la venta.."]) ?>
            </td>
            <td><?= $p->pago_id?></td>
            <td><?= $p->venta_id?></td>
            <td><?= $p->antes?></td>
            <td><?= $p->monto_pagado?></td>
            <td><?= $p->adeudo?></td>

        </tr>
    <?php endforeach;?>
    </tbody>
</table>