<div class="row justify-content-center">
    <div class="col-md-8">
        <canvas id="nuevo" style="width:50%; height:200px;"></canvas>
    </div>
</div>


<script>

    const ctx = document.getElementById('nuevo').getContext('2d');
    const nuevo = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [
                'Otros métodos','hola'
            ],
            datasets: [{
                label: 'Porcentaje de Ventas',
                data: [6,10],
                backgroundColor: [
                    'rgba(75, 192, 192, 0.7)',
                    'rgba(255, 159, 64, 0.7)',
                ],
                borderColor: [
                    'rgba(75, 192, 192, 1)',
                    'rgba(255, 159, 64, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'Participación de Producto en Ventas'
                }
            }
        }
    });
</script>