<div class="row justify-content-center">
    <div class="col-md-8">
        <canvas id="productChart" style="width:100%; height:400px;"></canvas>
    </div>
</div>


<script>


    const ctx = document.getElementById('productChart').getContext('2d');
    const productChart = new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: [
                'Otros métodos','<?=$metodos->nombre?>'
            ],
            datasets: [{
                label: 'Porcentaje de Ventas',
                data: [6,10],
                backgroundColor: [
                    'rgba(75, 192, 192, 0.7)',
                    'rgba(255, 159, 64, 0.7)',
                ],
                borderColor: [
                    'rgba(75, 192, 192, 1)',
                    'rgba(255, 159, 64, 1)',
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'top',
                },
                title: {
                    display: true,
                    text: 'Participación de Producto en Ventas'
                }
            }
        }
    });
</script>