<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard | SBU</title>

    <!-- Custom fonts for this template-->
    <link href="<?=URL_APP?>/default/public/libs/startbootstrap/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">


    <!-- Custom styles for this template-->
    <link href="<?=URL_APP?>/default/public/libs/startbootstrap/css/sb-admin-2.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>


    <!--Establecer la integración de SlimSelect-->
    <script src="<?=URL_APP?>/default/public/libs/slimselect/slimselect.min.js"></script>
    <link href="<?=URL_APP?>/default/public/libs/slimselect/slimselect.css" rel="stylesheet" />


    <!--Establecer la integración de JQuery-->
    <script src="<?=URL_APP?>/default/public/libs/JQuery/jquery-3.7.1.min.js"></script>


    <!--Establecer la conexión al DataTables-->
    <link rel="stylesheet" href="https://cdn.datatables.net/2.2.2/css/dataTables.dataTables.css" />
    <script src="https://cdn.datatables.net/2.2.2/js/dataTables.js"></script>

    <!--Filepond para imagenes-->
<!--    <link href="--><!--/default/public/libs/filepond/filepond.css" rel="stylesheet" />-->
<!--    <script src="--><!--/default/public/libs/filepond/filepond.js"></script>-->

    <link href="https://unpkg.com/filepond/dist/filepond.css" rel="stylesheet"/>
    <link href="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.css" rel="stylesheet" />
    <!-- add before </body> -->
    <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
    <script src="https://unpkg.com/filepond/dist/filepond.js"></script>




</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

    <?php View::partial("adminlte/sidebar")?>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">


            <?php View::partial("adminlte/topbar")?>

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!-- Page Heading -->
                <!--<h1 class="h3 mb-4 text-gray-800"><?=$title?></h1>-->
                <!-- Page Heading -->
                <h2 class="h4 mb-4 text-gray-800"><?=$subtitle?></h2>
                <?php View::content() ?>

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

        <?php View::partial("adminlte/footer")?>

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<?php View::partial("adminlte/cierresesion")?>

<!-- Bootstrap core JavaScript-->
<script src="<?=URL_APP?>/default/public/libs/startbootstrap/vendor/jquery/jquery.min.js"></script>
<script src="<?=URL_APP?>/default/public/libs/startbootstrap/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="<?=URL_APP?>/default/public/libs/startbootstrap/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="<?=URL_APP?>/default/public/libs/startbootstrap/js/sb-admin-2.min.js"></script>

<script>
    let table = new DataTable('.myTable', {
        // config options...
    });
</script>

<script>
    // Get a reference to the file input element
    const inputElement = document.querySelector('input[FilePond="1"]');

    // Create the FilePond instance
    const pond = FilePond.create(inputElement, {
        allowMultiple: true,
        storeAsFile: true,
    });

    // Easy console access for testing purposes
    window.pond = pond;
</script>

<script>
    new SlimSelect({
        select: '.selectElement'
    })
</script>

<script>
    new SlimSelect({
        select: '#single'
    })
</script>

</body>

</html>