<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar(); ?>

    </div>
    <div class="col-1">
        <?= Formbs::link_regresar("Detalle Venta",  "detallesVentas/registrar", "🔍"); ?>
    </div>
</div>
<br>
<h2>Detalles de las Ventas</h2>
<table class="table table-striped table-hover myTable">
    <thead>
    <tr>
        <th>Id</th>
        <th>Id de Venta</th>
        <th>Id de Productos</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($detallesVentas as $p):?>
        <tr>
            <td>
                <?= Html::link("detallesVentas/ver/{$p->id}", "Ver", ["title" => "Ir a producto.."]) ?>
            </td>
            <td><?= $p->ventas_id?></td>
            <td><?= $p->productos_id?></td>
            <td><?= $p->cantidad?></td>
            <td><?= $p->subtotal?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>