<h2>Acciones</h2>

<div class="row">
    <div class="col-1">
        <?= Formbs::link_regresar("Detalles",  "detallesVentas"); ?>
    </div>
</div>
<br>

<h1>No. <?= $detallesVentas->id?></h1>

<ul>
    <li><?=$detallesVentas->ventas_id?></li>
    <li><?=$detallesVentas->productos_id?></li>
    <li><?=$detallesVentas->cantidad?></li>
    <li><?=$detallesVentas->subtotal?></li>
</ul>

<a href="/kumbiaphp/default/public/detallesVentas" class="btn btn-primary">Ir a Detalles de las Ventas</a>