<div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
        <div class="row no-gutters align-items-center">
            <div class="col mr-2">
                <h4 class="text-primary text-uppercase mb-1">
                    Comentario General:</h4>
                <br>
                <h6 class="card-title"><?=$ComentarioGImprimir?></h6>

            </div>
        </div>
    </div>
</div>