<h4 class="mt-4">Ventas Pendientes de Pago</h4>

<form action="<?=URL_APP?>/default/public/pagos/finalizar/<?=$cliente->id?>">
<table class="table table-sm table-hover">
    <thead>
        <tr>
            <th></th>
            <th>Fecha</th>
            <th>Total</th>
            <th>Abonado</th>
            <th>Por Pagar</th>
            <th>A Pagar</th>
            <th>Comentario Por Venta</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($ventas as $v): ?>
        <tr>
            <td><?=$v->id?></td>
            <td><?=$v->created_at?></td>
            <td><?=($v->total)?></td>
            <td><?=($v->total - $v->por_pagar)?></td>
            <td><?=$v->por_pagar?></td>
            <td> <input name="ventas[<?=$v->id?>]" type="text"></td>
            <td> <input name="comentarios[<?=$v->id?>]" type="text"></td>
        </tr>

        <?php endforeach; ?>

    </tbody>
</table>

    <div class="row">
        <div class="col-2">
            <label>Comentario General:  </label>
            <input name="comentarioGeneral" type="text">
        </div>
        <div class="col-2">
            <label>Método de Pago *</label>

            <!-- Options -->
            <select id="single" name="Metodo">
                <?php foreach ($metodos as $m):?>
                    <option value="<?=$m->id?>"><?=$m->nombre?></option>
                <?php endforeach;?>
            </select>
        </div>
    </div>

    <br><br>

    <button type="submit" class="btn btn-primary">💳 Pagar</button>

</form>